server:
  port: 8081
  error:
    path: /error #usado en el ExceptionHandling

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_spring_security_jwt_backend?serverTimezone=America/Lima
    username: admin
    password: magadiflo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'